# Student Performance - Grade

In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Load the dataset

In [ ]:
df = pd.read_csv("student_performance_grade.csv")

,Student_ID,Age,Gender,Hours_Studied,Attendance,Sleep_Hours,Stress_Level,Screen_Time,Previous_GPA,Part_Time_Job,Study_Method,Diet_Quality,Internet_Quality,Extracurricular,Tutoring_Sessions_Per_Week,Family_Income_Level,Exam_Anxiety_Score,Grade
0,STU00001,17,Female,8.20,80.0,7.3,2.3,3.2,3.07,No,Online,Average,Average,Yes,3,High,1.8,A
1,STU00002,22,Male,4.07,69.2,7.9,3.6,0.5,2.66,Yes,Offline,Average,Good,No,2,Middle,1.0,A
2,STU00003,23,Female,5.07,74.2,6.7,2.6,4.7,3.27,No,Hybrid,Average,Good,No,1,Middle,4.2,A
3,STU00004,22,Female,5.82,82.5,3.7,3.3,2.3,2.87,No,Offline,Average,Excellent,No,0,Middle,3.6,A
4,STU00005,21,Male,3.42,90.8,7.4,7.0,3.1,2.82,Yes,Offline,Average,Good,No,2,Middle,4.5,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,STU07996,18,Female,6.45,93.6,9.7,5.4,5.9,3.28,No,Online,Poor,Excellent,Yes,3,Middle,3.8,A
7996,STU07997,20,Non-Binary,0.80,94.4,7.6,6.7,2.2,3.73,Yes,Offline,Poor,Good,Yes,2,Middle,4.5,B
7997,STU07998,19,Female,3.76,96.4,6.8,6.9,3.1,1.81,No,Hybrid,Poor,Good,No,0,Low,2.2,C
7998,STU07999,20,Female,3.87,79.2,8.2,8.2,4.9,3.36,No,Hybrid,Good,Excellent,Yes,2,Low,3.1,A
7999,STU08000,23,Female,6.87,74.5,4.9,2.0,2.4,2.48,Yes,Offline,Good,Good,Yes,3,Middle,3.0,A

# 2. Understanding the dataset

In [6]:
df.head()

,Student_ID,Age,Gender,Hours_Studied,Attendance,Sleep_Hours,Stress_Level,Screen_Time,Previous_GPA,Part_Time_Job,Study_Method,Diet_Quality,Internet_Quality,Extracurricular,Tutoring_Sessions_Per_Week,Family_Income_Level,Exam_Anxiety_Score,Grade
0,STU00001,17,Female,8.20,80.0,7.3,2.3,3.2,3.07,No,Online,Average,Average,Yes,3,High,1.8,A
1,STU00002,22,Male,4.07,69.2,7.9,3.6,0.5,2.66,Yes,Offline,Average,Good,No,2,Middle,1.0,A
2,STU00003,23,Female,5.07,74.2,6.7,2.6,4.7,3.27,No,Hybrid,Average,Good,No,1,Middle,4.2,A
3,STU00004,22,Female,5.82,82.5,3.7,3.3,2.3,2.87,No,Offline,Average,Excellent,No,0,Middle,3.6,A
4,STU00005,21,Male,3.42,90.8,7.4,7.0,3.1,2.82,Yes,Offline,Average,Good,No,2,Middle,4.5,B

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student_ID                  8000 non-null   str
 1   Age                         8000 non-null   int64
 2   Gender                      8000 non-null   str
 3   Hours_Studied               8000 non-null   float64
 4   Attendance                  8000 non-null   float64
 5   Sleep_Hours                 8000 non-null   float64
 6   Stress_Level                8000 non-null   float64
 7   Screen_Time                 8000 non-null   float64
 8   Previous_GPA                8000 non-null   float64
 9   Part_Time_Job               8000 non-null   str
 10  Study_Method                8000 non-null   str
 11  Diet_Quality                8000 non-null   str
 12  Internet_Quality            8000 non-null   str
 13  Extracurricular             8000 non-null   str
 14  Tutoring_Sessions_Per_Week  8000 non-null   int64
 15  Family_Income_Level         8000 non-null   str
 16  Exam_Anxiety_Score          8000 non-null   float64
 17  Grade                       8000 non-null   str
dtypes: float64(7), int64(2), str(9)
memory usage: 1.1 MB

In [8]:
df.describe()

,Age,Hours_Studied,Attendance,Sleep_Hours,Stress_Level,Screen_Time,Previous_GPA,Tutoring_Sessions_Per_Week,Exam_Anxiety_Score
count,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000
mean,20.494375,4.983845,79.933375,6.989125,5.014175,4.024525,2.992408,1.700625,4.494238
std,2.285962,1.951715,9.656594,1.192898,1.940126,1.481908,0.489530,1.112836,1.685571
min,17.000000,0.020000,43.300000,3.000000,1.000000,0.500000,1.500000,0.000000,1.000000
25%,18.000000,3.680000,73.400000,6.200000,3.700000,3.000000,2.670000,1.000000,3.300000
50%,20.500000,4.980000,80.100000,7.000000,5.000000,4.000000,2.990000,2.000000,4.400000
75%,22.000000,6.312500,86.600000,7.800000,6.300000,5.000000,3.330000,2.000000,5.600000
max,24.000000,12.000000,100.000000,10.000000,10.000000,9.600000,6.700000,5.000000,10.000000

In [9]:
df.isnull().sum()

Student_ID                    0
Age                           0
Gender                        0
Hours_Studied                 0
Attendance                    0
Sleep_Hours                   0
Stress_Level                  0
Screen_Time                   0
Previous_GPA                  0
Part_Time_Job                 0
Study_Method                  0
Diet_Quality                  0
Internet_Quality              0
Extracurricular               0
Tutoring_Sessions_Per_Week    0
Family_Income_Level           0
Exam_Anxiety_Score            0
Grade                         0
dtype: int64

In [10]:
df.dtypes

Student_ID                        str
Age                             int64
Gender                            str
Hours_Studied                 float64
Attendance                    float64
Sleep_Hours                   float64
Stress_Level                  float64
Screen_Time                   float64
Previous_GPA                  float64
Part_Time_Job                     str
Study_Method                      str
Diet_Quality                      str
Internet_Quality                  str
Extracurricular                   str
Tutoring_Sessions_Per_Week      int64
Family_Income_Level               str
Exam_Anxiety_Score            float64
Grade                             str
dtype: object

# 3. Execute the numerical columns

In [11]:
numerical_df = df.select_dtypes(include=["int64", "float64"])
numerical_df.columns

Index(['Age', 'Hours_Studied', 'Attendance', 'Sleep_Hours', 'Stress_Level',
       'Screen_Time', 'Previous_GPA', 'Tutoring_Sessions_Per_Week',
       'Exam_Anxiety_Score'],
      dtype='str')

# 4. Execute the Categorical columns

In [13]:
categorical_df = df.select_dtypes(include=["object", "string"])
categorical_df.columns

Index(['Student_ID', 'Gender', 'Part_Time_Job', 'Study_Method', 'Diet_Quality',
       'Internet_Quality', 'Extracurricular', 'Family_Income_Level', 'Grade'],
      dtype='str')

##  - Analysis

In [14]:
numerical_df.describe()

,Age,Hours_Studied,Attendance,Sleep_Hours,Stress_Level,Screen_Time,Previous_GPA,Tutoring_Sessions_Per_Week,Exam_Anxiety_Score
count,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000
mean,20.494375,4.983845,79.933375,6.989125,5.014175,4.024525,2.992408,1.700625,4.494238
std,2.285962,1.951715,9.656594,1.192898,1.940126,1.481908,0.489530,1.112836,1.685571
min,17.000000,0.020000,43.300000,3.000000,1.000000,0.500000,1.500000,0.000000,1.000000
25%,18.000000,3.680000,73.400000,6.200000,3.700000,3.000000,2.670000,1.000000,3.300000
50%,20.500000,4.980000,80.100000,7.000000,5.000000,4.000000,2.990000,2.000000,4.400000
75%,22.000000,6.312500,86.600000,7.800000,6.300000,5.000000,3.330000,2.000000,5.600000
max,24.000000,12.000000,100.000000,10.000000,10.000000,9.600000,6.700000,5.000000,10.000000

In [15]:
categorical_df.describe()

,Student_ID,Gender,Part_Time_Job,Study_Method,Diet_Quality,Internet_Quality,Extracurricular,Family_Income_Level,Grade
count,8000,8000,8000,8000,8000,8000,8000,8000,8000
unique,8000,3,2,3,3,4,2,3,5
top,STU00001,Male,No,Offline,Average,Good,No,Middle,A
freq,1,3906,4803,3170,3980,3266,4381,3912,4475

In [16]:
df["Grade"].value_counts()

Grade
A       4475
B       2212
C       1053
D        226
Fail      34
Name: count, dtype: int64

In [17]:
df["Grade"].value_counts(normalize=True) * 100

Grade
A       55.9375
B       27.6500
C       13.1625
D        2.8250
Fail     0.4250
Name: proportion, dtype: float64

In [19]:
df.groupby("Grade")["Hours_Studied"].agg(["mean", "min","max"])

           mean   min    max
Grade
A      5.912436  0.65  12.00
B      4.287048  0.20  10.22
C      3.211054  0.05   8.72
D      2.193186  0.02   7.20
Fail   1.551765  0.04   4.64

In [20]:
df.groupby("Grade")["Exam_Anxiety_Score"].agg(["mean", "std"])

           mean       std
Grade
A      3.881475  1.481733
B      4.859810  1.492944
C      5.753276  1.490892
D      6.747345  1.488509
Fail   7.391176  1.358780